### ISSUE TITLE
Projection issue with WARW

### ISSUE THREAD

**Issue by brunj7** [benfasoli/stiltread#1]
Hi

I am trying to use this package to process WRF-ARW ARL data (https://www.ready.noaa.gov/data/archives/wrf27km/README.TXT). However, I am facing projection issues and I am not sure why. It seems the header is read correctly, but I wonder if some of the projection assumptions differ from the one used in this dataset (I am not familiar with STILT).

here is a code sample:

```r
library(stiltread)
library(raster)
library(leaflet)

data_file = "wrfout_d01_20200101.ARL"
URL <- paste0("ftp://arlftp.arlhq.noaa.gov/pub/archives/wrf27km/2020/", data_file)
download.file(URL, destfile = data_file)

date <- strsplit(data_file, "[_.]")[[1]][3]

datuvar <- 'U10M'
vvar <- 'V10M'
yy <- substr(date, 3,4)
mm <- substr(date, 5,6)
dd <- substr(date, 7,8)
hh <- 1

uv <- read_met_wind("wrfout_d01_20200101.ARL", 
                    yy = yy,
                    mm = mm,
                    dd = dd,
                    hh = hh,
                    lvl = 0)

leaflet() %>%
  addProviderTiles('CartoDB.Positron') %>%
  addRasterImage(uv$v, opacity = 0.5, colors = viridis::viridis(16))
```

<img width="454" alt="Screen Shot 2020-07-30 at 11 35 24 PM" src="https://user-images.githubusercontent.com/5761340/89007347-6d24c680-d2bd-11ea-8cd0-cecdf89ab293.png">

Note that I do get projection warnings when running the code

```
In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
```

I have GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0 installed

**Comment by benfasoli** [comment]
Give the most recent build a try and let me know if the fix works for you.

**Comment by brunj7** [comment]
Yes, it did fix the problem!!

<img width="577" alt="Screen Shot 2020-07-31 at 8 45 45 AM" src="https://user-images.githubusercontent.com/5761340/89052260-4e98ec80-d30a-11ea-8581-4186b22c6a5a.png">

Thank you so much for your help and this great package!
